# generated by fastapi-codegen:
#   filename:  ./api/api-spec.yaml
#   timestamp: 2025-09-27T14:40:30+00:00

from __future__ import annotations

from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel


class DocumentDto(BaseModel):
    id: Optional[str] = None
    filename: Optional[str] = None


class LocationDto(BaseModel):
    id: Optional[str] = None
    address: Optional[str] = None


class UserDto(BaseModel):
    id: Optional[str] = None
    name: Optional[str] = None
    email: Optional[str] = None
    password: Optional[str] = None


class EntityDto(BaseModel):
    id: Optional[str] = None
    name: Optional[str] = None


class UserUserIdCatCatIdDocumentPostRequest(BaseModel):
    file: Optional[bytes] = None


class UserUserIdCatCatIdEventPostRequest(BaseModel):
    eventId: Optional[str] = None


class UserUserIdCatCatIdEventEventIdEntityPostRequest(BaseModel):
    entityId: Optional[str] = None


class EventDto(BaseModel):
    id: Optional[str] = None
    title: Optional[str] = None
    summary: Optional[str] = None
    date: Optional[datetime] = None
    location: Optional[LocationDto] = None
    entities: Optional[List[EntityDto]] = None


class CatDto(BaseModel):
    id: Optional[str] = None
    title: Optional[str] = None
    ownerId: Optional[str] = None
    documents: Optional[List[DocumentDto]] = None
    events: Optional[List[EventDto]] = None
