// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};

export type CatDto = {
    id?: string;
    title?: string;
    description?: string;
    ownerId?: string;
    documents?: Array<DocumentDto>;
    events?: Array<EventDto>;
};

export type DocumentDto = {
    id?: string;
    filename?: string;
};

export type EventDto = {
    id?: string;
    title?: string;
    summary?: string;
    date?: string;
    location?: LocationDto;
    entities?: Array<EntityDto>;
};

export type LocationDto = {
    id?: string;
    address?: string;
};

export type UserDto = {
    id?: string;
    name?: string;
    email?: string;
    password?: string;
};

export type EntityDto = {
    id?: string;
    name?: string;
};

export type GetUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user';
};

export type GetUserResponses = {
    /**
     * List of users
     */
    200: Array<UserDto>;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type PostUserData = {
    body: UserDto;
    path?: never;
    query?: never;
    url: '/user';
};

export type PostUserResponses = {
    /**
     * User created
     */
    201: UserDto;
};

export type PostUserResponse = PostUserResponses[keyof PostUserResponses];

export type DeleteUserByUserIdData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/user/{userId}';
};

export type DeleteUserByUserIdResponses = {
    /**
     * User deleted
     */
    204: void;
};

export type DeleteUserByUserIdResponse = DeleteUserByUserIdResponses[keyof DeleteUserByUserIdResponses];

export type GetUserByUserIdData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/user/{userId}';
};

export type GetUserByUserIdErrors = {
    /**
     * User not found
     */
    404: unknown;
};

export type GetUserByUserIdResponses = {
    /**
     * User found
     */
    200: UserDto;
};

export type GetUserByUserIdResponse = GetUserByUserIdResponses[keyof GetUserByUserIdResponses];

export type GetUserByUserIdCatData = {
    body?: never;
    path: {
        userId: string;
    };
    query?: never;
    url: '/user/{userId}/cat';
};

export type GetUserByUserIdCatResponses = {
    /**
     * List of cats
     */
    200: Array<CatDto>;
};

export type GetUserByUserIdCatResponse = GetUserByUserIdCatResponses[keyof GetUserByUserIdCatResponses];

export type PostUserByUserIdCatData = {
    body: CatDto;
    path: {
        userId: string;
    };
    query?: never;
    url: '/user/{userId}/cat';
};

export type PostUserByUserIdCatResponses = {
    /**
     * Cat created
     */
    201: CatDto;
};

export type PostUserByUserIdCatResponse = PostUserByUserIdCatResponses[keyof PostUserByUserIdCatResponses];

export type DeleteUserByUserIdCatByCatIdData = {
    body?: never;
    path: {
        userId: string;
        catId: string;
    };
    query?: never;
    url: '/user/{userId}/cat/{catId}';
};

export type DeleteUserByUserIdCatByCatIdResponses = {
    /**
     * Cat deleted
     */
    204: void;
};

export type DeleteUserByUserIdCatByCatIdResponse = DeleteUserByUserIdCatByCatIdResponses[keyof DeleteUserByUserIdCatByCatIdResponses];

export type GetUserByUserIdCatByCatIdData = {
    body?: never;
    path: {
        userId: string;
        catId: string;
    };
    query?: never;
    url: '/user/{userId}/cat/{catId}';
};

export type GetUserByUserIdCatByCatIdErrors = {
    /**
     * Cat not found
     */
    404: unknown;
};

export type GetUserByUserIdCatByCatIdResponses = {
    /**
     * Cat found
     */
    200: CatDto;
};

export type GetUserByUserIdCatByCatIdResponse = GetUserByUserIdCatByCatIdResponses[keyof GetUserByUserIdCatByCatIdResponses];

export type PutUserByUserIdCatByCatIdData = {
    body: CatDto;
    path: {
        userId: string;
        catId: string;
    };
    query?: never;
    url: '/user/{userId}/cat/{catId}';
};

export type PutUserByUserIdCatByCatIdResponses = {
    /**
     * Cat updated
     */
    200: CatDto;
};

export type PutUserByUserIdCatByCatIdResponse = PutUserByUserIdCatByCatIdResponses[keyof PutUserByUserIdCatByCatIdResponses];

export type GetUserByUserIdCatByCatIdDocumentData = {
    body?: never;
    path: {
        userId: string;
        catId: string;
    };
    query?: never;
    url: '/user/{userId}/cat/{catId}/document';
};

export type GetUserByUserIdCatByCatIdDocumentResponses = {
    /**
     * List of documents
     */
    200: Array<DocumentDto>;
};

export type GetUserByUserIdCatByCatIdDocumentResponse = GetUserByUserIdCatByCatIdDocumentResponses[keyof GetUserByUserIdCatByCatIdDocumentResponses];

export type PostUserByUserIdCatByCatIdDocumentData = {
    body: {
        file?: Blob | File;
    };
    path: {
        userId: string;
        catId: string;
    };
    query?: never;
    url: '/user/{userId}/cat/{catId}/document';
};

export type PostUserByUserIdCatByCatIdDocumentResponses = {
    /**
     * Document uploaded
     */
    201: DocumentDto;
};

export type PostUserByUserIdCatByCatIdDocumentResponse = PostUserByUserIdCatByCatIdDocumentResponses[keyof PostUserByUserIdCatByCatIdDocumentResponses];

export type GetUserByUserIdCatByCatIdDocumentByDocumentIdData = {
    body?: never;
    path: {
        userId: string;
        catId: string;
        documentId: string;
    };
    query?: never;
    url: '/user/{userId}/cat/{catId}/document/{documentId}';
};

export type GetUserByUserIdCatByCatIdDocumentByDocumentIdErrors = {
    /**
     * Document not found
     */
    404: unknown;
};

export type GetUserByUserIdCatByCatIdDocumentByDocumentIdResponses = {
    /**
     * Document found
     */
    200: DocumentDto;
};

export type GetUserByUserIdCatByCatIdDocumentByDocumentIdResponse = GetUserByUserIdCatByCatIdDocumentByDocumentIdResponses[keyof GetUserByUserIdCatByCatIdDocumentByDocumentIdResponses];

export type DeleteUserByUserIdCatByCatIdEventData = {
    body?: never;
    path: {
        userId: string;
        catId: string;
    };
    query: {
        eventId: string;
    };
    url: '/user/{userId}/cat/{catId}/event';
};

export type DeleteUserByUserIdCatByCatIdEventResponses = {
    /**
     * Event deleted
     */
    204: void;
};

export type DeleteUserByUserIdCatByCatIdEventResponse = DeleteUserByUserIdCatByCatIdEventResponses[keyof DeleteUserByUserIdCatByCatIdEventResponses];

export type GetUserByUserIdCatByCatIdEventData = {
    body?: never;
    path: {
        userId: string;
        catId: string;
    };
    query?: never;
    url: '/user/{userId}/cat/{catId}/event';
};

export type GetUserByUserIdCatByCatIdEventResponses = {
    /**
     * List of events
     */
    200: Array<EventDto>;
};

export type GetUserByUserIdCatByCatIdEventResponse = GetUserByUserIdCatByCatIdEventResponses[keyof GetUserByUserIdCatByCatIdEventResponses];

export type PostUserByUserIdCatByCatIdEventData = {
    body: {
        eventId?: string;
    };
    path: {
        userId: string;
        catId: string;
    };
    query?: never;
    url: '/user/{userId}/cat/{catId}/event';
};

export type PostUserByUserIdCatByCatIdEventResponses = {
    /**
     * Event associated with cat
     */
    200: unknown;
};

export type DeleteUserByUserIdCatByCatIdEntityData = {
    body?: never;
    path: {
        userId: string;
        catId: string;
    };
    query: {
        entityId: string;
    };
    url: '/user/{userId}/cat/{catId}/entity';
};

export type DeleteUserByUserIdCatByCatIdEntityResponses = {
    /**
     * Entity deleted
     */
    204: void;
};

export type DeleteUserByUserIdCatByCatIdEntityResponse = DeleteUserByUserIdCatByCatIdEntityResponses[keyof DeleteUserByUserIdCatByCatIdEntityResponses];

export type GetUserByUserIdCatByCatIdEntityData = {
    body?: never;
    path: {
        userId: string;
        catId: string;
    };
    query?: never;
    url: '/user/{userId}/cat/{catId}/entity';
};

export type GetUserByUserIdCatByCatIdEntityResponses = {
    /**
     * List of entities
     */
    200: Array<EntityDto>;
};

export type GetUserByUserIdCatByCatIdEntityResponse = GetUserByUserIdCatByCatIdEntityResponses[keyof GetUserByUserIdCatByCatIdEntityResponses];

export type PostUserByUserIdCatByCatIdEntityData = {
    body: EntityDto;
    path: {
        userId: string;
        catId: string;
    };
    query?: never;
    url: '/user/{userId}/cat/{catId}/entity';
};

export type PostUserByUserIdCatByCatIdEntityResponses = {
    /**
     * Entity created
     */
    201: EntityDto;
};

export type PostUserByUserIdCatByCatIdEntityResponse = PostUserByUserIdCatByCatIdEntityResponses[keyof PostUserByUserIdCatByCatIdEntityResponses];

export type GetUserByUserIdCatByCatIdEntityByEntityIdData = {
    body?: never;
    path: {
        userId: string;
        catId: string;
        entityId: string;
    };
    query?: never;
    url: '/user/{userId}/cat/{catId}/entity/{entityId}';
};

export type GetUserByUserIdCatByCatIdEntityByEntityIdErrors = {
    /**
     * Entity not found
     */
    404: unknown;
};

export type GetUserByUserIdCatByCatIdEntityByEntityIdResponses = {
    /**
     * Entity found
     */
    200: EntityDto;
};

export type GetUserByUserIdCatByCatIdEntityByEntityIdResponse = GetUserByUserIdCatByCatIdEntityByEntityIdResponses[keyof GetUserByUserIdCatByCatIdEntityByEntityIdResponses];

export type PostUserByUserIdCatByCatIdEventByEventIdEntityData = {
    body: {
        entityId?: string;
    };
    path: {
        userId: string;
        catId: string;
        eventId: string;
    };
    query?: never;
    url: '/user/{userId}/cat/{catId}/event/{eventId}/entity';
};

export type PostUserByUserIdCatByCatIdEventByEventIdEntityResponses = {
    /**
     * Entity linked to event
     */
    200: unknown;
};

export type GetUserByUserIdCatByCatIdLocationData = {
    body?: never;
    path: {
        userId: string;
        catId: string;
    };
    query?: never;
    url: '/user/{userId}/cat/{catId}/location';
};

export type GetUserByUserIdCatByCatIdLocationResponses = {
    /**
     * List of locations
     */
    200: Array<LocationDto>;
};

export type GetUserByUserIdCatByCatIdLocationResponse = GetUserByUserIdCatByCatIdLocationResponses[keyof GetUserByUserIdCatByCatIdLocationResponses];
